spring:
  datasource:
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE

  testWhileIdle: true
  validationQuery: SELECT 1

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext